[project]
name = "lidar_prod"
dynamic = ["version"]
description = "A 3D semantic segmentation production tool to augment rule- based Lidar classification with AI and databases."
readme = "README.md"
authors = [
    { name = "Charles GAYDON", email = "charles.gaydon@gmail.com" }
]
maintainers = [
  {name = "Charles GAYDON", email = "charles.gaydon@gmail.com"},
  {name = "Michel DAAB"},
  {name = "Léa VAUCHIER", email = "lea.vauchier@ign.fr"}
]
license = {file = "LICENSE"}
dependencies = []  # assume an environment as described in environment.yml

[metadata]
project_template = "https://github.com/ashleve/lightning-hydra-template"
copyright = "2022, Institut National de l'Information Géographique et Forestière"

[project.urls]
Documentation = "https://ignf.github.io/lidar-prod/"
Repository = "https://github.com/IGNF/lidar-prod"
Issues = "https://github.com/IGNF/lidar-prod/issues"
Changelog = "https://github.com/IGNF/lidar-prod/blob/main/CHANGELOG.md"

[tool.setuptools.dynamic]
version = {attr = "lidar_prod.version.__version__"}

[tool.setuptools]
packages = [ "lidar_prod" ]

[tool.black]
line-length = 99
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''

[tool.isort]
profile = "black"
filter_files = true
known_first_party = ["lidar_prod"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]

[tool.pytest.ini_options]
python_files = 'tests/*'
log_cli = true
addopts = """
    --cov "./lidar_prod/"
    --cov-fail-under 92
    --cov-report html
    """
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning",
    "ignore::FutureWarning",
    "ignore::optuna.exceptions.ExperimentalWarning"
]

[tool.coverage.run]
branch = true
omit = ['lidar_prod/run.py']

[tool.coverage.report]
show_missing = true
