_target_: lidar_prod.tasks.building_validation.BuildingValidator

building_validation_thresholds_pickle: /path/to/best_trial.pkl

data_format: ${data_format}
use_final_classification_codes: true


bd_uni_connection_params:
  _target_: lidar_prod.tasks.utils.BDUniConnectionParams
  host: serveurbdudiff.ign.fr
  user: invite
  pwd: 28de#
  bd_name: bduni_france_consultation

cluster:
  tolerance: 0.5  # meters
  min_points: 10

bd_uni_request:
  buffer: 50

rules:
  min_confidence_confirmation: 0.768
  min_frac_confirmation: 0.732
  min_uni_db_overlay_frac: 0.508
  min_confidence_refutation: 0.872
  min_frac_refutation: 0.964
