_target_: lidar_prod.tasks.building_validation.BuildingValidator

building_validation_thresholds_pickle: /path/to/best_trial.pkl

data_format: ${data_format}
use_final_classification_codes: true


bd_uni_connection_params:
  _target_: lidar_prod.tasks.utils.BDUniConnectionParams
  host: serveurbdudiff.ign.fr
  user: invite
  pwd: 28de#
  bd_name: bduni_france_consultation

cluster:
  tolerance: 0.5  # meters
  min_points: 10

bd_uni_request:
  buffer: 50

# TODO: update min_frac_confirmation_factor_if_bd_uni_overlay and others after optimization...
thresholds:
  min_confidence_confirmation: 0.6400365762003571  # min proba to validate a point
  min_frac_confirmation: 0.779844069887882  # min fractin of confirmed points per group for confirmation
  min_frac_confirmation_factor_if_bd_uni_overlay: 0.5894477997785892  # relaxation factor to min proba when point is under BDUni vector
  min_uni_db_overlay_frac: 0.5041941489707767  # min fraction of points  under BDUni vector per group for confirmation
  min_confidence_refutation: 0.7477148092712739 # min proba to refute a point
  min_frac_refutation: 0.7979734453001499   # min fractin of refuted points per group for confirmation
  min_entropy_uncertainty: 0.884546947499147   # min entropy to flag a point as uncertain
  min_frac_entropy_uncertain: 0.7271206406484895   # min fractin of uncertain points (based on entropy) per group to flag as uncertain
