_target_: lidar_prod.tasks.building_validation.BuildingValidator

building_validation_thresholds_pickle: /path/to/best_trial.pkl

candidate_buildings_codes: [6]  # a list
use_final_classification_codes: True

data_format: ${data_format}

bd_uni_connection_params:
  _target_: lidar_prod.tasks.utils.BDUniConnectionParams
  host: serveurbdudiff.ign.fr
  user: invite
  pwd: 28de#
  bd_name: bduni_france_consultation

cluster:
  tolerance: 0.5  # meters
  min_points: 10

bd_uni_request:
  buffer: 50

# TODO: make a package group to make it loadable by pickel directly at instantiation time.
rules:
  min_confidence_confirmation: 0.768
  min_frac_confirmation: 0.732
  min_uni_db_overlay_frac: 0.508
  min_confidence_refutation: 0.872
  min_frac_refutation: 0.964

codes:
  detailed:
    unclustered: 6  # refuted
    ia_refuted: 33  # refuted
    ia_refuted_and_db_overlayed: 34  # unsure
    both_unsure: 35  # unsure
    ia_confirmed_only: 36  # confirmed
    db_overlayed_only: 37  # confirmed
    both_confirmed: 38  # confirmed
  final:
    unsure: 35  # unsure
    not_building: 33  # refuted
    building: 38  # confirmed

