_target_: lidar_prod.tasks.building_validation.BuildingValidator

data_format: ${data_format}
use_final_classification_codes: true

shp_path: null

bd_uni_connection_params:
  _target_: lidar_prod.tasks.utils.BDUniConnectionParams
  host: serveurbdudiff.ign.fr
  user: invite
  pwd: 28de#
  bd_name: bduni_france_consultation

cluster:
  tolerance: 0.5  # meters
  min_points: 10

bd_uni_request:
  buffer: 50

# TODO: update min_frac_confirmation_factor_if_bd_uni_overlay and others after optimization...
thresholds:
  min_confidence_confirmation: 0.37574976186264664  # min proba to validate a point
  min_frac_confirmation: 0.6661410185371994  # min fractin of confirmed points per group for confirmation
  min_frac_confirmation_factor_if_bd_uni_overlay: 0.8820746597006655  # relaxation factor to min proba when point is under BDUni vector
  min_uni_db_overlay_frac: 0.5041941489707767  # min fraction of points  under BDUni vector per group for confirmation
  min_confidence_refutation: 0.5212204710813311 # min proba to refute a point
  min_frac_refutation: 0.9613067360728214   # min fractin of refuted points per group for confirmation
  min_entropy_uncertainty: 0.6286345539969987   # min entropy to flag a point as uncertain
  min_frac_entropy_uncertain: 0.9057081151270139   # min fractin of uncertain points (based on entropy) per group to flag as uncertain
