_target_: lidar_prod.tasks.building_identification.BuildingIdentifier

data_format: ${data_format}

min_building_proba: ${building_validation.application.thresholds.min_confidence_confirmation}
min_frac_confirmation_factor_if_bd_uni_overlay: ${building_validation.application.thresholds.min_frac_confirmation_factor_if_bd_uni_overlay}

cluster:
  min_points: 200  # Large so that small artefact are ignored
  tolerance: 1  # meters
  is3d: false  # group in 2d for better detection

