tile_size_meters: 1000
crs_prefix: "EPSG:"
crs: 2154


las_channel_names:
  # input
  classification: classification  #las format
  cluster_id: ClusterID  #pdal-defined
  uni_db_overlay: BDTopoOverlay  # user-defined
  ai_building_proba: building  # user-defined

  # output - for now custom channels
  macro_candidate_building_groups: CandidateBuildingGroups
  ai_building_identified: AICandidateBuilding

codes:
  candidates:
    building: [202]