tile_size_meters: 1000
crs_prefix: "EPSG:"
crs: 2154

# To connect logic between application tasks
las_channel_names:
  # input
  classification: classification  #las format
  cluster_id: ClusterID  #pdal-defined
  uni_db_overlay: BDTopoOverlay  # user-defined
  ai_building_proba: building  # user-defined

  # custom channels
  candidate_buildings_flag: CandidateBuildingsFlag
  macro_candidate_building_groups: CandidateBuildingGroups
  ai_building_identified: Group

codes:
  candidates:
    building: [202]

defaults:
  - cleaning: default.yaml