name: CICD

on:
#  push:
#    branches: [test_ci]
  pull_request:
    branches: [main]

jobs:
  test_push:
    runs-on: self-hosted

    steps:

    - name: Checkout branch       
      uses: actions/checkout@v2
    
    - name: unit testing
      run: pytest --ignore=actions-runner --ignore="notebooks"

    - name: test full module
#      run: python /home/MDaab/code/Segmentation-Validation-Model/run.py --config-path logs/V3.0/.hydra --config-name config.yaml task=predict hydra.run.dir='/home/MDaab/code/Segmentation-Validation-Model' prediction.resume_from_checkpoint='logs/V3.0/checkpoints/epoch_013.ckpt' prediction.src_las='/home/MDaab/Data/dataSet/trainvaltest/922000_6307000.las' prediction.best_trial_pickle_path='/home/MDaab/code/Segmentation-Validation-Model/logs/V3.0/best_trial.pkl' prediction.output_dir='output_prediction' prediction.mts_auto_detected_code=6 datamodule.batch_size=50 trainer.gpus=0
      run: python run.py --config-path /var/data/cicd/extra_files/V3.0/.hydra --config-name config.yaml task=predict hydra.run.dir='/var/data/cicd/actions-runner_2/lidar-prod-quality-control' prediction.resume_from_checkpoint='/var/data/cicd/extra_files/V3.0/checkpoints/epoch_013.ckpt' prediction.src_las='/var/data/dataSet/trainvaltest/922000_6307000.las' prediction.best_trial_pickle_path='/var/data/cicd/extra_files/V3.0/best_trial.pkl' prediction.output_dir='output_prediction' prediction.mts_auto_detected_code=6 datamodule.batch_size=50 trainer.gpus=0