name: CICD

# on:
#   pull_request:
#     branches: [main]

on: push

jobs:
  test_push:
    runs-on: self-hosted

    steps:

    - name: Checkout branch       
      uses: actions/checkout@v2

    # - name: Setup conda env
    #   run: bash -i CI/setup_env.sh

    # - name: Check code neatness (linter)
    #   run: flake8

    # - name: unit testing
    #   run: pytest --ignore=actions-runner --ignore="notebooks"

    # - name: Package install
    #   run: bash -i CI/install_as_a_package.sh

    # - name: Run on a small point cloud
    #   run: bash -i CI/run_app.sh

    # - name: Evaluate decisions on single LAS
    #   run: bash -i CI/evaluate_bv_single_las.sh

    # - name: Delete the anaconda environment
    #   run: conda env remove -n lidar_prod

    - name: build docker image       
      run: docker build -t predict_im .

    - name: Check code neatness (linter)
      run: docker run predict_im flake8

    - name: unit testing
      run: docker run predict_im pytest --ignore=actions-runner --ignore="notebooks"

    - name: test full run
      run: docker run -v /var/data/cicd/CICD_github_assets:/CICD_github_assets predict_im 
      
