# Workflow name
name: "Documentation Build"

# Event that must trigger the workflow
on:
  push:
    branches:
      - main  # <- only on main branch
      - add-documentation  # <- on this branch until documentation is merged once in main.

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    # Task to do when launching the workflow
    steps:

      # 1. First get the repository source

      - name: "Checkout"
        uses: actions/checkout@v2

      # 2. Sphinx part : install tool and dependencies

      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.12

      # Here we update base environment direcly
      # to avoid tricky activations
      - name: "Install Python dependencies"
        run: conda env update -f bash/setup_environment/requirements.yml --name base

      - name: "Build Sphinx Doc"
        working-directory: ./docs/
        run: make html

      # 3. Déploiement sur les Github Pages

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages     # <- Branch where generated doc files will be commited
          FOLDER: docs/build/html/  # <- Dir where .nojekyll is created and from which to deploy github pages.
